### ISSUE TITLE
Question about using the face++ API

### ISSUE THREAD

**Issue by clementf2b** [FacePlusPlus/MegviiFacepp-Android-SDK#10]
I want to use the detectAPI. How can I get the request? This project only use the authAPI to call it. How can I change this? Thank you.

**Comment by Liangyang0929** [comment]
Faceapp api is written in C language. This SDK is just a simple wrapper of faceapp api and show how to use it. Moreover, faceapp api is not free, you must pay for it if you want to use.  You can visit their website for detail information, by the way, their website has English version.

**Comment by jionkang** [comment]
This is SDK for mobile,please read the guide to access it,and we alse has demo to run it.
