### ISSUE TITLE
就是想跑一下demo

### ISSUE THREAD

**Issue by wangkunlin** [FacePlusPlus/MegviiFacepp-Android-SDK#15]
就是想跑一下demo 就这么难么？又是copy这，又是copy那的， 然后还得根据是否需要联网手动注释代码，然后还得填key，难道就不能提供测试的key 么？你这运行demo的成本也太高了。

**Comment by Chaoba** [comment]
这确实是以前遗留下来的问题，我们也早已发现这个问题。接下来抽出空来的话我们会改进一下这些库之间的依赖，方便开发者。谢谢你的支持和理解。

**Comment by wangkunlin** [comment]
有个  问题，ios 的离线 sdk 能开启 人脸属性，但是 android 的不行，是什么原因？都是从官网下载的sdk

**Comment by Chaoba** [comment]
model里面没有包含这项功能。

**Comment by Chaoba** [comment]
Demo和sdk已经重构了，请按照readme里提示的去官网下载个model并且申请key和secret就可以运行demo了。很抱歉无法提供测试的key。
