### ISSUE TITLE
离线授权不通过

### ISSUE THREAD

**Issue by mostz** [FacePlusPlus/MegviiFacepp-Android-SDK#19]
按照文档说明配置离线授权
在执行这句代码的时候返回值是1
Facepp.getSDKAuthType(ConUtil.getFileContent(this, R.raw.megviifacepp_0_4_7_model));
导致后面都无法继续

**Comment by jeesezh** [comment]
请问这是怎么解决的？

**Comment by Chaoba** [comment]
离线和在线是由模型的类型决定的。现在官网上下的是在线授权版本。
