### ISSUE TITLE
出现如下错误，不知道是怎么回事

### ISSUE THREAD

**Issue by liu738633885** [FacePlusPlus/MegviiFacepp-Android-SDK#28]
10-19 17:56:28.174 13156-13156/? E/Zygote: v2
10-19 17:56:28.174 13156-13156/? I/libpersona: KNOX_SDCARD checking this for 10194
10-19 17:56:28.174 13156-13156/? I/libpersona: KNOX_SDCARD not a persona
10-19 17:56:28.184 13156-13156/? W/SELinux: Function: selinux_compare_spd_ram, index[1], priority [2], priority version is VE=SEPF_SECMOBILE_6.0.1_0027
10-19 17:56:28.184 13156-13156/? E/Zygote: accessInfo : 0
10-19 17:56:28.184 13156-13156/? W/SELinux: SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.megvii.awesomedemo.facepp 
10-19 17:56:28.184 13156-13156/? I/art: Late-enabling -Xcheck:jni
10-19 17:56:28.204 13156-13156/com.megvii.awesomedemo.facepp D/TimaKeyStoreProvider: TimaSignature is unavailable
10-19 17:56:28.204 13156-13156/com.megvii.awesomedemo.facepp D/ActivityThread: Added TimaKeyStore provider
10-19 17:56:28.304 13156-13156/com.megvii.awesomedemo.facepp W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.megvii.awesomedemo.facepp-2/split_lib_dependencies_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.megvii.awesomedemo.facepp-2@split_lib_dependencies_apk.apk@classes.dex) because non-0 exit status
10-19 17:56:28.464 13156-13156/com.megvii.awesomedemo.facepp W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.megvii.awesomedemo.facepp-2/split_lib_slice_0_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.megvii.awesomedemo.facepp-2@split_lib_slice_0_apk.apk@classes.dex) because non-0 exit status
10-19 17:56:28.514 13156-13156/com.megvii.awesomedemo.facepp W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.megvii.awesomedemo.facepp-2/split_lib_slice_1_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.megvii.awesomedemo.facepp-2@split_lib_slice_1_apk.apk@classes.dex) because non-0 exit status
10-19 17:56:28.564 13156-13156/com.megvii.awesomedemo.facepp W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.megvii.awesomedemo.facepp-2/split_lib_slice_2_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.megvii.awesomedemo.facepp-2@split_lib_slice_2_apk.apk@classes.dex) because non-0 exit status
10-19 17:56:28.614 13156-13156/com.megvii.awesomedemo.facepp W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.megvii.awesomedemo.facepp-2/split_lib_slice_3_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.megvii.awesomedemo.facepp-2@split_lib_slice_3_apk.apk@classes.dex) because non-0 exit status
10-19 17:56:28.664 13156-13156/com.megvii.awesomedemo.facepp W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.megvii.awesomedemo.facepp-2/split_lib_slice_4_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.megvii.awesomedemo.facepp-2@split_lib_slice_4_apk.apk@classes.dex) because non-0 exit status
10-19 17:56:28.714 13156-13156/com.megvii.awesomedemo.facepp W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.megvii.awesomedemo.facepp-2/split_lib_slice_5_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.megvii.awesomedemo.facepp-2@split_lib_slice_5_apk.apk@classes.dex) because non-0 exit status
10-19 17:56:28.764 13156-13156/com.megvii.awesomedemo.facepp W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.megvii.awesomedemo.facepp-2/split_lib_slice_6_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.megvii.awesomedemo.facepp-2@split_lib_slice_6_apk.apk@classes.dex) because non-0 exit status
10-19 17:56:28.824 13156-13156/com.megvii.awesomedemo.facepp W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.megvii.awesomedemo.facepp-2/split_lib_slice_7_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.megvii.awesomedemo.facepp-2@split_lib_slice_7_apk.apk@classes.dex) because non-0 exit status
10-19 17:56:28.874 13156-13156/com.megvii.awesomedemo.facepp W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.megvii.awesomedemo.facepp-2/split_lib_slice_8_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.megvii.awesomedemo.facepp-2@split_lib_slice_8_apk.apk@classes.dex) because non-0 exit status
10-19 17:56:28.924 13156-13156/com.megvii.awesomedemo.facepp W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.megvii.awesomedemo.facepp-2/split_lib_slice_9_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.megvii.awesomedemo.facepp-2@split_lib_slice_9_apk.apk@classes.dex) because non-0 exit status
10-19 17:56:28.934 13156-13156/com.megvii.awesomedemo.facepp I/InstantRun: starting instant run server: is main process
10-19 17:56:28.934 13156-13156/com.megvii.awesomedemo.facepp V/InstantRun: Starting server socket listening for package com.megvii.awesomedemo.facepp on android.net.LocalSocketAddress@7988c08
10-19 17:56:28.934 13156-13156/com.megvii.awesomedemo.facepp V/InstantRun: Started server for package com.megvii.awesomedemo.facepp
10-19 17:56:29.014 13156-13156/com.megvii.awesomedemo.facepp D/SensorManager: registerListener :: 0, ICM20610 Acceleration Sensor, 200000, 0,  
10-19 17:56:29.134 13156-13156/com.megvii.awesomedemo.facepp W/ceshi: tmpSize.width===1920, tmpSize.height===1080
10-19 17:56:29.134 13156-13156/com.megvii.awesomedemo.facepp W/ceshi: tmpSize.width===1440, tmpSize.height===1080
10-19 17:56:29.134 13156-13156/com.megvii.awesomedemo.facepp W/ceshi: tmpSize.width===1280, tmpSize.height===720
10-19 17:56:29.134 13156-13156/com.megvii.awesomedemo.facepp W/ceshi: tmpSize.width===1088, tmpSize.height===1088
10-19 17:56:29.134 13156-13156/com.megvii.awesomedemo.facepp W/ceshi: tmpSize.width===1056, tmpSize.height===864
10-19 17:56:29.134 13156-13156/com.megvii.awesomedemo.facepp W/ceshi: tmpSize.width===960, tmpSize.height===720
10-19 17:56:29.134 13156-13156/com.megvii.awesomedemo.facepp W/ceshi: tmpSize.width===720, tmpSize.height===480
10-19 17:56:29.134 13156-13156/com.megvii.awesomedemo.facepp W/ceshi: tmpSize.width===640, tmpSize.height===480
10-19 17:56:29.134 13156-13156/com.megvii.awesomedemo.facepp W/ceshi: tmpSize.width===352, tmpSize.height===288
10-19 17:56:29.134 13156-13156/com.megvii.awesomedemo.facepp W/ceshi: tmpSize.width===320, tmpSize.height===240
10-19 17:56:29.134 13156-13156/com.megvii.awesomedemo.facepp W/ceshi: tmpSize.width===176, tmpSize.height===144
10-19 17:56:29.134 13156-13156/com.megvii.awesomedemo.facepp W/ceshi: Angle==90
10-19 17:56:29.174 13156-13156/com.megvii.awesomedemo.facepp E/mgf-c: nativeInit retcode: 104
10-19 17:56:29.174 13156-13156/com.megvii.awesomedemo.facepp A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 13156 (somedemo.facepp)
10-19 17:56:29.174 13156-13156/com.megvii.awesomedemo.facepp A/libc: Unable to open connection to debuggerd: Connection refused

**Comment by jionkang** [comment]
是不是在 init和config 之后调用了detect，看返回值像是没初始化
