### ISSUE TITLE
大神们帮忙看一下这个报错 Error:A problem occurred configuring project ':sdk'. 运行官方下载的as版本的demo报错，

### ISSUE THREAD

**Issue by mesenOne** [FacePlusPlus/MegviiFacepp-Android-SDK#29]
运行官方下载的as版本的最新demo就总是报Error:A problem occurred configuring project ':sdk'. 这个错，可是我该引用的都引用了

**Comment by jionkang** [comment]
有更详细的日志吗？这里sdk 只是as的一个module，所以问题应该是其他的引起的

**Comment by thelillianhu** [comment]
@mesenOne 请问你这个问题解决了么？

**Comment by Evey12** [comment]
遇到了同样的问题，运行不起来，求帮助@mesenOne

**Comment by vikas0** [comment]
encountering the same problem, any help from the Face++ team?

**Comment by Duqiang1991** [comment]
local.properties加上ndk.dir试试看

**Comment by jionkang** [comment]
新的版本已经不需要ndk编译，当然如果熟悉ndk也可以使用ndk编译

**Comment by cnqiuxue** [comment]
encountering the same problem
