### ISSUE TITLE
联网授权失败，请检查网络或找服务商

### ISSUE THREAD

**Issue by shangshicc** [FacePlusPlus/MegviiFacepp-Android-SDK#31]
设备：红米note4x, Android6.+系统。
使用sdk：MegviiLicMgr-Android-SDK:0.3.0
申请的试用期key
在  licenseManager.takeLicenseFromNetwork回调中回调onFailed方法，错误码0,错误信息为null
关于联网授权部分使用的demo中代码（LoadingActivity）没做修改
请问是什么问题引起的

**Comment by jionkang** [comment]
请问有绑定包名吗，如果使用非联网授权的可以联系商务

**Comment by jionkang** [comment]
目前我只有在网络联网失败的时候才会出现，错误码0,错误信息为null
