### ISSUE TITLE
我觉得他们说的很对

### ISSUE THREAD

**Issue by kdsrsl** [FacePlusPlus/MegviiFacepp-Android-SDK#32]
这是我见过最垃圾的demo....

**Comment by songlongkuan** [comment]
这是我见过最垃圾的demo....

**Comment by jionkang** [comment]
由于ide的升级迭代，我们升级了sdk的demo，同时由于商务上的一些原因，底层库需要按照guide去申请，带来的不便很抱歉，如果按照指导有接入的问题我们很乐意去解决。
