### ISSUE TITLE
最后出现如下报错，不知道怎么解决了 

### ISSUE THREAD

**Issue by imaginefish** [FacePlusPlus/MegviiFacepp-Android-SDK#33]
Error:Execution failed for task ':sdk:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/armeabi-v7a/libMegviiFacepp-jni-0.4.7.so'

**Comment by jionkang** [comment]
应该是ndk版本的问题，升级下版本试下

**Comment by jionkang** [comment]
When I update to android studio 3.0.I meet this problem,first delete the jni.so  ,then modify cmake, to hide  this line  #set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${jnilibs}/${ANDROID_ABI}).    That will be  OK!
