### ISSUE TITLE
gradle是不是需要注意版本啊

### ISSUE THREAD

**Issue by panuniverse** [FacePlusPlus/MegviiFacepp-Android-SDK#35]
Error 1:
FAILURE: Build failed with an exception.

* Where:
Build file '/home/fuq/DesktopProject/Face++/MegviiFacepp-Android-SDK/build.gradle' line: 10

* What went wrong:
A problem occurred evaluating root project 'MegviiFacepp-Android-SDK'.
> Could not find method compile() for arguments [com.github.FacePlusPlus:MegviiFacepp-Android-SDK:0.4.7] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 0s

Error 2:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':demo:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 3s

**Comment by jionkang** [comment]
加入android {
lintOptions {
abortOnError false
}
}
或者用新的版本
