### ISSUE TITLE
运行gradle 时出现error

### ISSUE THREAD

**Issue by panuniverse** [FacePlusPlus/MegviiFacepp-Android-SDK#36]
* What went wrong:
Execution failed for task ':demo:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/megvii/facepp/sdk/BuildConfig;

**Comment by jionkang** [comment]
clean下工程
