### ISSUE TITLE
git clone 官方demo跑不起来.

### ISSUE THREAD

**Issue by DarkSherlock** [FacePlusPlus/MegviiFacepp-Android-SDK#42]
首先没依赖sdk module 所以FaceApp找不到，依赖后就可以了。但是，
    compile(name: 'MGLicenseManagerSDK-0.3.0', ext: 'aar')
    compile(name: 'MGFaceppSDK-0.5.2', ext: 'aar')
    compile project(':sdk')
    发现LicenseManager找不到了。
    将compile(name: 'MGLicenseManagerSDK-0.3.0', ext: 'aar')
   改为这个依赖  compile 'com.github.FacePlusPlus:MegviiLicMgr-Android-SDK:0.3.0' 就能成功导包，虽然导入的licenseManager.takeLicenseFromNetwork(）这个方法的参数类型发生了变化，自己修改了一下就OK 
但是运行demo的时候错误又双叒叕来了，
Program type already present: com.megvii.facepp.sdk.BuildConfig
Message{kind=ERROR, text=Program type already present: com.megvii.facepp.sdk.BuildConfig, sources=[Unknown source file], tool name=Optional.of(D8)}
请问这是什么鬼？？？
想加下技术群咨询一下 发现满人了，官方demo都跑不起来真是心累。。
希望尽快回复解决办法

**Comment by jionkang** [comment]
发现LicenseManager找不到了。
这个是在MGLicenseManagerSDK-0.3.0'这里面的。可以clean下工程，另外也可以拉取最新的代码
