### ISSUE TITLE
demo跑步起来

### ISSUE THREAD

**Issue by CharmMagic** [FacePlusPlus/MegviiFacepp-Android-SDK#43]
Error:Execution failed for task ':demo:transformNativeLibsWithMergeJniLibsForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/armeabi-v7a/libMegviiFacepp-0.4.7.so
  	File1: /Users/.android/build-cache/8d94a65593a4f54faf43a7e29dd7a480a4832e09/output/jni
  	File2: /Users/Downloads/MegviiFacepp-Android-SDK-0.4.7/sdk/build/intermediates/bundles/default/jni

**Comment by jionkang** [comment]
已上传新版本
另外如果用0.4.7可以这样子
packagingOptions {
        //打包时的相关配置

        pickFirst "lib/armeabi-v7a/libMegviiFacepp-jni-0.5.2.so"
        pickFirst "lib/arm64-v8a/libMegviiFacepp-jni-0.5.2.so"
